# GitHub Actions workflow for building and testing Delve on push events
# This workflow runs on both Windows and Ubuntu runners
# It builds the project, runs the test suite, and provides basic notifications

name: Build and Test Delve

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test-windows:
    name: Build and Test on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build-requirements.txt
      - name: Run build script
        run: python build.py
      - name: Run test suite
        run: |
          cd build\assemble
          fl.bat test

  build-and-test-linux:
    name: Build and Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install MariaDB Connector/C
        run: sudo apt-get update && sudo apt-get install -y libmariadb-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build-requirements.txt
      - name: Run build script
        run: python build.py
      - name: Run test suite
        run: |
          cd build/assemble
          ./fl test

# Notifications:
# - GitHub will show pass/fail in the UI and send email to repository watchers if enabled.
# - For custom notifications, add steps using actions for Slack, Discord, etc.
